apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
  labels:
    app: frontend-service
    app.kubernetes.io/name: frontend-service
    app.kubernetes.io/component: frontend
    app.kubernetes.io/part-of: opsgpt
    environment: dev
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: core-api-service-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
  labels:
    app: core-api-service
    app.kubernetes.io/name: core-api-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: opsgpt
    environment: dev
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: alert-ingestion-service-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
  labels:
    app: alert-ingestion-service
    app.kubernetes.io/name: alert-ingestion-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: opsgpt
    environment: dev
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ai-analysis-service-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
  labels:
    app: ai-analysis-service
    app.kubernetes.io/name: ai-analysis-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: opsgpt
    environment: dev
    azure.workload.identity/use: "true"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service-sa
  namespace: dev
  annotations:
    azure.workload.identity/client-id: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
  labels:
    app: notification-service
    app.kubernetes.io/name: notification-service
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: opsgpt
    environment: dev
    azure.workload.identity/use: "true"
