
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: core-api-service-spc
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
    keyvaultName: "opsgpt-kv-aasik-tf"
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    objects: |
      array:
        - |
          objectName: prod-database-url
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: prod-jwt-secret-key
          objectType: secret
          objectAlias: JWT_SECRET_KEY
        - |
          objectName: prod-internal-api-key
          objectType: secret
          objectAlias: INTERNAL_API_KEY
  secretObjects:
    - secretName: core-api-service-secret
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: JWT_SECRET_KEY
          key: JWT_SECRET_KEY
        - objectName: INTERNAL_API_KEY
          key: INTERNAL_API_KEY
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: alert-ingestion-service-spc
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
    keyvaultName: "opsgpt-kv-aasik-tf"
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    objects: |
      array:
        - |
          objectName: prod-database-url
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: prod-internal-api-key
          objectType: secret
          objectAlias: INTERNAL_API_KEY
  secretObjects:
    - secretName: alert-ingestion-service-secret
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: INTERNAL_API_KEY
          key: INTERNAL_API_KEY
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ai-analysis-service-spc
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
    keyvaultName: "opsgpt-kv-aasik-tf"
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    objects: |
      array:
        - |
          objectName: prod-database-url
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: prod-internal-api-key
          objectType: secret
          objectAlias: INTERNAL_API_KEY
        - |
          objectName: prod-azure-foundry-api-key
          objectType: secret
          objectAlias: AZURE_FOUNDRY_API_KEY
  secretObjects:
    - secretName: ai-analysis-service-secret
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: INTERNAL_API_KEY
          key: INTERNAL_API_KEY
        - objectName: AZURE_FOUNDRY_API_KEY
          key: AZURE_FOUNDRY_API_KEY
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: notification-service-spc
  namespace: prod
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "false"
    clientID: "6052dc97-db6d-4c5a-b64a-66b527c7732e"
    keyvaultName: "opsgpt-kv-aasik-tf"
    tenantId: "d8537334-bc24-4daf-95a8-bf4c9fb14394"
    objects: |
      array:
        - |
          objectName: prod-database-url
          objectType: secret
          objectAlias: DATABASE_URL
        - |
          objectName: prod-slack-webhook-url
          objectType: secret
          objectAlias: SLACK_WEBHOOK_URL
  secretObjects:
    - secretName: notification-service-secret
      type: Opaque
      data:
        - objectName: DATABASE_URL
          key: DATABASE_URL
        - objectName: SLACK_WEBHOOK_URL
          key: SLACK_WEBHOOK_URL
